/**
 * Author：zhoushuanglong
 * Time：2017/7/27
 * Description：index constants
 */

// 登陆
export const LOGIN = 'login'

// 面包屑
export const BREADCRUMB = 'breadcrumb'
// 导航
export const NAVIGATION = 'navigation'

// 游戏列表
export const GAMELIST = 'game-list'

// 帖子管理
export const POST = {
    'ADD_DATA': 'ADD_POST_DATA',
    'ADD_QUERY': 'ADD_POST_QUERY',
    'EDIT_USER_INFO': 'ADD_POST_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_POST_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_POST_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_POST_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_POST_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_POST_PAGE_DATA'
}

// 快讯管理
export const FLASH = {
    'ADD_DATA': 'ADD_FLASH_DATA',
    'ADD_QUERY': 'ADD_FLASH_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASH_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASH_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASH_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASH_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASH_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASH_PAGE_DATA'
}

// 发帖子用户管理
export const USERPOST = {
    'ADD_DATA': 'ADD_USERPOST_DATA',
    'ADD_QUERY': 'ADD_USERPOST_QUERY',
    'EDIT_USER_LIST_ITEM': 'EDIT_USER_LIST_ITEM',
    'EDIT_USER_POST_LIST_ITEM': 'EDIT_USER_POST_LIST_ITEM',
    'EDIT_COMMENT_LIST_ITEM': 'EDIT_COMMENT_LIST_ITEM',
    'DEL_USER_POST_LIST_ITEM': 'DEL_USER_POST_LIST_ITEM',
    'DEL_COMMENT_LIST_ITEM': 'DEL_COMMENT_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_USER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_USER_PAGE_DATA',
    'SET_POST_LIST_PAGE_DATA': 'SET_USER_POST_LIST_PAGE_DATA',
    'SET_COMMENT_LIST_PAGE_DATA': 'SET_USER_COMMENT_LIST_PAGE_DATA'
}

// 图片鉴别
export const IMGS = {
    'ADD_DATA': 'ADD_IMGS_DATA',
    'EDIT_SELECT_DATA': 'EDIT_IMGS_SELECT_DATA',
    'EDIT_LIST_ITEM': 'EDIT_IMGS_LIST_ITEM'
}

// 词条管理
export const LANGUAGE = {
    'ADD_DATA': 'ADD_LANGUAGE_DATA',
    'ADD_QUERY': 'ADD_LANGUAGE_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_LANGUAGE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LANGUAGE_LIST_ITEM',
    'EDIT_REPEAT_LIST_ITEM': 'EDIT_LANGUAGE_REPEAT_LIST_ITEM',
    'SELECT_REPEAT_LIST_ITEM': 'SELECT_LANGUAGE_REPEAT_LIST_ITEM'
}

// 游戏初始化
export const INITGAME = {
    'ADD_DATA': 'ADD_INITGAME_DATA',
    'ADD_QUERY': 'ADD_INITGAME_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_INITGAME_LIST_ITEM'
}

// 用户权限
export const AUTHORITY = {
    'ADD_DATA': 'ADD_AUTHORITY_DATA',
    'ADD_QUERY': 'ADD_AUTHORITY_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_AUTHORITY_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AUTHORITY_LIST_ITEM'
}
